// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-recent-reports.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_recent_reports_default = defineTool({
  name: "list_recent_reports",
  title: "List recent daily reports",
  description: "Return the signed-in user's most recent daily productivity reports (date, productivity_percent, tasks, notes).",
  inputSchema: {
    limit: z.number().int().min(1).max(90).optional().describe("Max number of reports to return (default 14).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client(ctx).from("daily_reports").select("date, productivity_percent, tasks, notes").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(limit ?? 14);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { reports: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-day-report.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_day_report_default = defineTool2({
  name: "get_day_report",
  title: "Get a specific day's report",
  description: "Fetch the signed-in user's daily report for a specific YYYY-MM-DD date.",
  inputSchema: {
    date: z2.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Local date in YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client2(ctx).from("daily_reports").select("date, productivity_percent, tasks, notes, version, created_at").eq("user_id", ctx.getUserId()).eq("date", date).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No report saved for ${date}.` }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { report: data }
    };
  }
});

// src/lib/mcp/tools/save-day-report.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var TaskSchema = z3.object({
  title: z3.string(),
  weight: z3.number(),
  completionPercent: z3.number(),
  category: z3.string().optional(),
  note: z3.string().optional()
});
var save_day_report_default = defineTool3({
  name: "save_day_report",
  title: "Save a daily report",
  description: "Create or update the signed-in user's daily report for a date. Computes productivity as sum(weight*completionPercent)/100.",
  inputSchema: {
    date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Local date in YYYY-MM-DD."),
    tasks: z3.array(TaskSchema).min(1).describe("Task entries with weight (0-100) and completionPercent (0-100)."),
    notes: z3.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ date, tasks, notes }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const productivity = Math.round(
      tasks.reduce((sum, t) => sum + t.weight * t.completionPercent / 100, 0) * 100
    ) / 100;
    const supa = client3(ctx);
    const { data, error } = await supa.from("daily_reports").upsert(
      {
        user_id: ctx.getUserId(),
        date,
        tasks,
        notes: notes ?? null,
        productivity_percent: productivity
      },
      { onConflict: "user_id,date" }
    ).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved ${date} \u2014 productivity ${productivity}%.` }],
      structuredContent: { report: data, productivity_percent: productivity }
    };
  }
});

// src/lib/mcp/tools/get-stats.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_stats_default = defineTool4({
  name: "get_productivity_stats",
  title: "Get productivity stats",
  description: "Summary stats for the signed-in user: average productivity over the last N days, best/worst days, day count.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).optional().describe("Lookback window in days (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const n = days ?? 30;
    const { data, error } = await client4(ctx).from("daily_reports").select("date, productivity_percent").eq("user_id", ctx.getUserId()).order("date", { ascending: false }).limit(n);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    if (rows.length === 0) {
      return { content: [{ type: "text", text: "No reports yet." }], structuredContent: { count: 0 } };
    }
    const avg = rows.reduce((s, r) => s + Number(r.productivity_percent ?? 0), 0) / rows.length;
    const best = rows.reduce((a, b) => Number(b.productivity_percent) > Number(a.productivity_percent) ? b : a);
    const worst = rows.reduce((a, b) => Number(b.productivity_percent) < Number(a.productivity_percent) ? b : a);
    const summary = {
      window_days: n,
      count: rows.length,
      average_productivity_percent: Math.round(avg * 100) / 100,
      best_day: best,
      worst_day: worst
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-goals.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.81.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
function client5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_goals_default = defineTool5({
  name: "list_goals",
  title: "List productivity goals",
  description: "Return the signed-in user's productivity goals.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await client5(ctx).from("productivity_goals").select("*").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { goals: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "eabsrzsexzphpsdbyiyq";
var mcp_default = defineMcp({
  name: "glow-mcp",
  title: "Glow \u2014 Daily Productivity",
  version: "0.1.0",
  instructions: "Tools for the Glow productivity app. Read and save the signed-in user's daily productivity reports, view stats, and list their goals. All tools act as the authenticated user; per-user data is protected by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_recent_reports_default, get_day_report_default, save_day_report_default, get_stats_default, list_goals_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
